sudo: false
language: php
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4
  - 7.0
  - 7.1

matrix:
  allow_failures:
    - php: nightly

env:
  - TRAVIS_NODE_VERSION="6"

cache:
  directories:
    - bower_components
    - node_modules

before_install:
  - composer self-update && composer --version
  - source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION && nvm use $TRAVIS_NODE_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

install:
  - npm install -g npm@latest
  - npm install -g bower gulp jscs
  - npm install
  - composer global require squizlabs/php_codesniffer

script:
  - npm rebuild node-sass
  - npm run build
  - npm run jshint
  - npm run jscs
